server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.101.99:3306/emms
      username: emms
      password: 123456
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
    mapper-locations: classpath:mapper/**/**.xml